### ISSUE TITLE
iOS XCUI: login flow hangs 600s behind Save Password dialog; iPad offline-queue attention affordance not observed

### ISSUE THREAD

**Issue by jpapiez** [OlyForge3D/PrintFarmer#2829]
Observed on iOS PR CI run [35494894657](https://github.com/OlyForge3D/PrintFarmer/actions/runs/35494894657) (branch `dev/jpapiez/wiring-update-scheduling`, PR #2804).

**These are not caused by #2804.** That PR changes 18 files, **zero** under `mobile/` -- it is backend host-update scheduling plus an admin cancel route. XCUI is also not a required status check. Filing so the failures are tracked rather than absorbed as noise.

Note that XCUI was **skipped** on every other recent PR run, so there is no recent green baseline for these tests. #2804 happens to be the branch where the matrix actually expanded.

## Failure 1 -- `LoginFlowUITests/testLoginTransitionsToOperatorShell` (both shard-1 jobs)

`Run login XCUI` runs only on `matrix.shard == 1`, so it executed exactly twice (iPhone + iPad) and **failed both times** -- a 100% failure rate, not a flake.

```
mobile/PrintFarmerUITests/LoginFlowUITests.swift:101: error:
  XCTAssertEqual failed: ("nil") is not equal to ("Optional(true)")
  - Authenticated shell did not finish launching within the test allowance;
    elapsed=600.2994392083333s;
    last operation=exists: navigation interruption: Save Password?;
    remaining=0.0s
```

The simulator raised the iOS **"Save Password?"** system dialog and the test consumed its entire 600 s allowance waiting behind it.

**Worth investigating:** `UIWaitBudgetTests` contains passing unit-level coverage for exactly this scenario --
`testAllowedAlertDismissalNeverChoosesSaveOrAnUnknownAlert` and
`testLatePasswordPromptIsDismissedOnceWithinOriginalNavigationBudget` both pass. So the dismissal policy is modelled and tested, but the real login flow still hung behind the prompt. The gap is between the modelled policy and its application in `LoginFlowUITests`, not in the policy itself.

Secondary concern: a single blocked assertion burning 600 s is a poor failure mode. The per-operation budget should fail fast once the interruption is unresolvable.

## Failure 2 -- `ColdOfflineShellUITests/testOfflineQueueRemainsReachableFromAccountWhileOffline` (iPad shard 4)

```
mobile/PrintFarmerUITests/ColdOfflineShellUITests.swift:137: error: failed
  - Missing tab.attention or sidebar.attention;
    elapsed=8.439204208333308s;
    last operation=application shell snapshot;
    remaining=0.0s; last snapshot: not observed
```

Distinct from failure 1 -- fails fast (8.4 s) on a missing attention affordance. The other three `ColdOfflineShellUITests` in the same shard passed.

## Requested work

1. Make `LoginFlowUITests` actually apply the Save Password interruption handling that `UIWaitBudgetTests` already models, and add coverage binding the two together so the modelled policy cannot pass while the real flow hangs.
2. Fail fast on an unresolvable navigation interruption instead of consuming the full 600 s allowance.
3. Diagnose `tab.attention` / `sidebar.attention` not being observed on iPad in the offline-queue path.
4. Consider why XCUI is skipped on most PRs -- the suite has little effective coverage if it rarely expands.
## Research handoff (2026-09-23)

Research completed and findings are recorded in [issue comment #5801103417](https://github.com/OlyForge3D/PrintFarmer/issues/2829#issuecomment-5801103417), whose verified UTF-8 body digest is `91a0663f9ed45731c77306b14b5f0b0b6a625158017fa61c62265766ab279fcf` (6,356 bytes). The investigation confirmed two distinct XCUI problems: the login flow can remain blocked by the iOS Save Password interruption despite passing policy-model tests, and the iPad offline-queue attention affordance is not observed. It also confirmed that XCUI is skipped on most recent PR runs, limiting regression coverage.

**Implementation plan:** `squad:hudson` should bind `LoginFlowUITests` to the modeled interruption handling, fail fast on unresolvable navigation interruptions, diagnose and cover the iPad offline-queue attention affordance, and address the CI XCUI coverage gap. Research changed no repository files; this remains the implementation issue.

**Comment by jpapiez** [comment]
"Triage: classified as `type:bug` / `priority:p2` from the issue's stated scope and linked evidence. Existing owner retained; first step: reproduce the dialog and attention affordance failures on the approved simulator. Rationale: iOS UI test environment failures obscure login and offline-queue coverage"

**Comment by jpapiez** [comment]
## Research outcome

The issue conflates failed jobs with failed individual tests. Existing interruption handling is wired and demonstrably works on iPad. The iPhone 600-second hang is real, but logs do not establish that a Save Password dialog caused it. The offline-queue failure is a first-snapshot timeout, not proof that Attention is absent. No implementation was performed.

### Login interruption binding and coverage

At pinned HEAD, `mobile/PrintFarmerUITests/LoginFlowUITests.swift:20-23` already supplies `["Save Password?": "Not Now"]` and enables one unchanged-alert retry; line 101 calls `waitForAuthenticatedShell()`. `mobile/PrintFarmerUITests/PrintFarmerUITests.swift:1180-1240` binds those overrides to real `app.alerts[title]` observation, snapshot policy selection, live button hit testing, and dismissal. The named `mobile/PrintFarmerTests/UIWaitBudgetTests.swift` does not exist: UIWaitBudgetTests is in `mobile/PrintFarmerUITests/PrintFarmerUITests.swift:318+`, selected in XCUI shard 4 for both device families (`ios-pr-ci.yml:263,306`), not the PrintFarmerTests-only unit job.

Both LoginFlowUITests.swift and the shared PrintFarmerUITests.swift are byte-for-byte identical between pinned HEAD and failing run head `ed46a13b3d1638f73d68efa615efc255914cab6c`.

Run `35494894657`: iPad shard 1 job `106038271226` logs `Tap "Not Now" Button` and `testLoginTransitionsToOperatorShell` passes at 51.764s; the job fails separately because `testCanTypeInLoginFields` loses keyboard focus at LoginFlowUITests.swift:71. iPhone shard 1 job `106038271213` fails transition after 600.969s (`elapsed=600.2994392083333s`), with 1,482 `Find the Target Application` lines and no `Not Now` lines. `Checking existence of "Save Password?" Alert` is a query label, not positive existence. The last operation does not prove a visible blocking dialog; repeated snapshots point to unready/unrecognized shell observations. Targeted shell-state evidence is needed.

Coverage should exercise the real base-class adapter with actual login policy: no-alert ready shell; observed allowed alert -> exact Not Now -> disappearance -> ready shell; late alert; unsupported alert; failed/non-hittable dismissal; exhausted unchanged retry; and an alert absent from the queried application root. Run actual login transition on approved iPhone and iPad. Keep the iPad keyboard-focus failure distinct from navigation dismissal.

### Fail-fast behavior

`UIWaitBudget` (`PrintFarmerUITests.swift:6-132`) stops starting operations after a monotonic deadline but cannot cancel an in-flight synchronous XCUI query. `setUp:1047-1057` creates its budget from executionTimeAllowance; `waitForAuthenticatedShell:1071-1087` passes the whole test budget. `waitForShell:69-109` also keeps polling the same alert after permitted dismissal attempts are exhausted. Use a finite navigation/readiness child budget bounded by the original test deadline, plus finite disappearance grace after the last permitted dismissal; fail with explicit reason, last shell state, alert existence, selected application root, attempt count, and last operation. Preserve fail-closed handling for unknown/changed/rejected alerts and keep XCTest's external watchdog for blocked remote calls. Add fake-clock tests for early exit, no post-failure remote actions, and unchanged absolute deadline. Choose the child budget from approved runtime measurements; the successful iPad transition took 51.764s including login input.

### iPad offline queue

`ColdOfflineShellUITests.swift:136-156` goes directly from launch to an 8-second destination lookup without `waitsForNavigationReadiness`; the base default is false (`PrintFarmerUITests.swift:1043`). Other cold-shell tests perform the tab-bar/startup probe and Oversight navigation first. Job `106038271172` starts at 07:35:47Z, first target-app snapshot is at t=6.45s, and failure is at t=14.89s (`elapsed=8.439204208333308s`, last operation application shell snapshot, last snapshot not observed). `UIWaitBudget.perform:28-33` discards results returned after deadline; `waitForShell:73-74` does not record such a result. This is not evidence of removed identifiers or missing offline routing.

Production still renders sidebar buttons with `tab.sidebarAccessibilityIdentifier` (`ContentView.swift:227-294`); Floor sidebar contains Attention subject to `attentionEnabled` (`AppDestination.swift:74-157`). Give authenticated bootstrap bounded readiness, including positively observed sidebar reveal, before destination-specific budget; preserve diagnostics for over-budget snapshots without accepting them as success or issuing new queries. Retain Attention -> Account -> Offline Queue assertions; add setup/adapter binding coverage for cold-offline suite and verify iPad collapsed/visible sidebar and iPhone. Exact discarded historical snapshot content is unknown.

### XCUI skip behavior

The actual owner is `.github/workflows/ios-pr-ci.yml`, not `ci.yml`. It triggers on PR events; `scripts/ci/select-ios-build.sh:43-142` uses the PR merge-base diff. Unit tests (`ios-pr-ci.yml:128-134`) and eight XCUI jobs (`:212-220`) skip when the selector is false; XCUI also waits for passing unit tests. Recent samples `35906331133` (2026-09-23, fix-ralph-durable-evidence) and `35743656465` (2026-09-22, fix-ralph-owned-session-inventory) log `should_run=false reason=no iOS-relevant paths changed`. These are intentional path-selection skips, not failed matrix expansion. Backend-only #2804 expanded because its 18-file diff includes `src/infra/Dtos/HostUpdateSchedulingDtos.cs`, matching the selector's shared API wire-contract regex. Run `35494894657` selector job `106036082950` confirms `should_run=true reason=iOS-relevant paths changed`. A green Build check alone is not XCUI evidence. Any periodic/manual baseline or required XCUI gate needs a separate CI-policy change with selector/workflow tests; do not unconditionally run eight macOS jobs or modify unrelated `ci.yml`.

### Disposition and blockers

All four questions have source/log-backed findings and implementation guidance; no bug is claimed fixed. Exact iPhone unready-shell/root cause and exact discarded iPad snapshot still require targeted runtime evidence. No simulator runs or new tests were executed. No files, commits, PRs, labels, or child sessions were created; working tree is clean.

**Comment by jpapiez** [comment]
Hudson implementation started. Read the full research handoff: the alert policy is already wired, and the historical iPhone log does not prove a visible Save Password dialog. Approved iOS 26.5 (23F77) iPhone 17 and iPad Pro 13-inch (M5) resolved under Xcode 27.0 (27A266a). Baseline focused LoginFlowUITests and ColdOfflineShellUITests are running. Plan: diagnose observed shell state; bound readiness/dismissal failure and retain late-snapshot diagnostics; opt cold-offline setup into readiness before its destination budget; bind adapter coverage to actual login configuration; validate both families plus units, then current-head Bishop/Vasquez review. Intentional path-based XCUI skips will be documented rather than expanding eight macOS jobs without a CI-policy requirement. App-managed branch: jpapiez-hudson-fixing-xcui-login-hang.
