### ISSUE TITLE
Follow-up: deferred review findings from host-update scheduler and manual update UI

### ISSUE THREAD

**Issue by jpapiez** [OlyForge3D/PrintFarmer#2812]
Non-blocking findings accepted during review of the host-update scheduler wiring (PR #2804) and the manual server-update UI (PR #2808). All were explicitly deferred; none blocks the merged behaviour.

## Scheduler status projection — `src/infra/Services/HostUpdates/ProductionHostUpdateAdapters.cs`

1. **`_ =>` switch arm mislabels a non-`IHostUpdateAvailability` executor.** An executor that does not implement `IHostUpdateAvailability` falls to the default arm and is reported as not provisioned. Currently unreachable in production and fail-closed, so the behaviour is safe, but the reason string is wrong for that shape and would mislead anyone diagnosing a future executor implementation.
2. **No guard against an empty or whitespace `UnavailableReason`.** An executor reporting `IsAvailable: false` with an empty reason yields an empty string in `Reasons`, which is projected to the UI as a blank entry. Treat empty/whitespace as equivalent to a missing reason.
3. **New test name advertises its weakest assertion.** `SchedulerStatusHolder_ReportsAdmittedReasonOnceForAvailableExecutor` names the `Count == 1` assertion, which passes on the pre-fix code because `.Distinct(StringComparer.Ordinal)` collapses the duplicate. The assertion that actually binds the fix is `Assert.Null(status.Executor.Reason)`. A future reader diagnosing a failure is pointed at the wrong assertion. Rename toward the binding behaviour.
4. **`.Distinct(StringComparer.Ordinal)` masks duplicate-source defects.** Pre-existing, not introduced by #2804. It is what made the duplicate `Admitted` entry invisible in the first place. Worth revisiting whether de-duplication belongs at projection time or whether contributors should simply not emit duplicates.

## Contract test fragility — `src/tests/Farm.Web.Api.Tests/Integration/SystemInfoIntegrationTests.cs:164`

`Should().Equal` is an ordered exact-sequence assertion over the projected `Reasons`. The scheduler reason is appended conditionally on `hasAttempt`, so if the integration fixture ever yields a non-null `LastAttemptAt` the sequence gains an element and the test fails for a reason unrelated to what it is guarding. Either pin the fixture's `LastAttemptAt` explicitly or assert on set membership plus the executor token's terminal position.

## UI test binding — `src/Web/ReactApp/src/test/features/admin/InstallerUpdatesExperience.test.tsx`

The storage-survival assertion reads `localStorage` directly. A remount-based assertion — unmount, remount, assert the restored state through the rendered UI — would bind the behaviour users actually depend on rather than the storage mechanism. Accepted as sufficient for merge and explicitly classed as follow-up hardening by the reviewer who raised it.

Relates to #2757
